### ISSUE TITLE
Doesn't Display Information

### ISSUE THREAD

**Issue by BPowell76** [WazeDev/WME-Place-Interface-Enhancements#15]
WME PIE is no longer showing me any of the properties checked off (name, lock level, size, etc.). I'm only able to see place names because Waze supports it natively now.  I'm running Google Chrome v110.0.5481.104 (64-bit official). I'm able to get the names and lock levels to show by toggling the checkbox, but it only refreshes for the screen and once I pan away nothing is showing again.

I'm not sure if this is due to the new WME edition, but here's a list of installed plugins/scripts I'm also running:

- WME Toolbox
- WME Advanced Closures
- WME ClickSaver
- WME Color Highlights
- WME GIS Layers
- WME Junction Angle Info
- WME LaneTools
- WME Place Harmonizer
- WME Road Shield Assistant
- WME Road Shield Helper
- WME Speedhelper
- WME UR-MP Tracking
- WME US Government Boundaries
- WME Validator

Installed, but inactive:

- WME Fix UI Memorial Edition
- WME OpenMaps
- WME Place NavPoints
- WME RA Util

**Comment by justins83** [comment]
This was due to WME updates and has since been resolved.
