### ISSUE TITLE
Natural Features Icon

### ISSUE THREAD

**Issue by TheCre8r** [WazeDev/WME-Place-Interface-Enhancements#8]
Natural Features Icon does not show up properly
Vanilla WME
![image](https://user-images.githubusercontent.com/6027150/113496649-c76bcc00-94c9-11eb-80ef-861ae93d2a99.png)
PIE Enabled
![image](https://user-images.githubusercontent.com/6027150/113496663-e8342180-94c9-11eb-91a0-c4c1c4cb7994.png)

**Comment by TheCre8r** [comment]
If possible in the adjustment, please also change the CSS for 
`#edit-buttons .residential .item-icon::after {
background-position: -15px -37px;`
to 
`background-position: -15px -38px;`
and change the 
`<span style="font-size:12px;">Residence / Home</span>`
to just
`Residence / Home`
This makes it the correct size and moves the house to the correct location
* Before is in screenshot for the issue report
* After CSS changes below:
![image](https://user-images.githubusercontent.com/6027150/113496805-4ca3b080-94cb-11eb-9ae5-a15f80d3c4a4.png)

**Comment by justins83** [comment]
Fixed in latest version, 20201.05.05.01
